2025-04-29 13:27:29,443 INFO    MainThread:6389 [wandb_setup.py:_flush():68] Current SDK version is 0.19.10
2025-04-29 13:27:29,443 INFO    MainThread:6389 [wandb_setup.py:_flush():68] Configure stats pid to 6389
2025-04-29 13:27:29,443 INFO    MainThread:6389 [wandb_setup.py:_flush():68] Loading settings from /Users/paris/.config/wandb/settings
2025-04-29 13:27:29,443 INFO    MainThread:6389 [wandb_setup.py:_flush():68] Loading settings from /Users/paris/Downloads/VAE/wandb/settings
2025-04-29 13:27:29,443 INFO    MainThread:6389 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-04-29 13:27:29,443 INFO    MainThread:6389 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /Users/paris/Downloads/VAE/wandb/run-20250429_132729-amwl5o90/logs/debug.log
2025-04-29 13:27:29,444 INFO    MainThread:6389 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /Users/paris/Downloads/VAE/wandb/run-20250429_132729-amwl5o90/logs/debug-internal.log
2025-04-29 13:27:29,444 INFO    MainThread:6389 [wandb_init.py:monkeypatch_ipython():643] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x1abeab380>
2025-04-29 13:27:29,444 INFO    MainThread:6389 [wandb_init.py:init():852] calling init triggers
2025-04-29 13:27:29,446 INFO    MainThread:6389 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'beta': 1e-05, 'decoder_arch': hidden_dim: 128
name: Mlp
num_layers: 3
output_dim: 784
, 'encoder_arch': activation: !!python/name:jax._src.nn.functions.gelu ''
hidden_dim: 64
latent_dim: 16
name: MlpEncoder
num_layers: 3
, 'eps_dim': 16, 'input_dim': (1, 784), 'job_type': 'train', 'logging': log_every_steps: 100
log_losses: true
, 'optim': beta1: 0.9
beta2: 0.999
decay_rate: 0.9
decay_steps: 1000
eps: 1.0e-08
learning_rate: 0.001
optimizer: Adam
, 'seed': 4, 'training': batch_size: 32
num_epochs: 20
num_mc_samples: 4
, 'wandb': name: null
project: MNIST
tag: null
, '_wandb': {}}
2025-04-29 13:27:29,446 INFO    MainThread:6389 [wandb_init.py:init():893] starting backend
2025-04-29 13:27:29,446 INFO    MainThread:6389 [wandb_init.py:init():897] sending inform_init request
2025-04-29 13:27:29,483 INFO    MainThread:6389 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-04-29 13:27:29,483 INFO    MainThread:6389 [wandb_init.py:init():907] backend started and connected
2025-04-29 13:27:29,495 INFO    MainThread:6389 [wandb_run.py:_label_probe_notebook():1369] probe notebook
2025-04-29 13:27:29,496 INFO    MainThread:6389 [wandb_init.py:init():1002] updated telemetry
2025-04-29 13:27:29,498 INFO    MainThread:6389 [wandb_init.py:init():1026] communicating run to backend with 90.0 second timeout
2025-04-29 13:27:29,783 INFO    MainThread:6389 [wandb_init.py:init():1101] starting run threads in backend
2025-04-29 13:27:30,098 INFO    MainThread:6389 [wandb_run.py:_console_start():2566] atexit reg
2025-04-29 13:27:30,099 INFO    MainThread:6389 [wandb_run.py:_redirect():2414] redirect: wrap_raw
2025-04-29 13:27:30,099 INFO    MainThread:6389 [wandb_run.py:_redirect():2483] Wrapping output streams.
2025-04-29 13:27:30,100 INFO    MainThread:6389 [wandb_run.py:_redirect():2506] Redirects installed.
2025-04-29 13:27:30,102 INFO    MainThread:6389 [wandb_init.py:init():1147] run started, returning control to user process
2025-04-29 13:27:30,103 INFO    MainThread:6389 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-04-29 13:27:30,118 INFO    MainThread:6389 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-04-29 13:27:30,118 INFO    MainThread:6389 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-04-29 13:27:30,119 INFO    MainThread:6389 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-04-29 13:27:30,132 INFO    MainThread:6389 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-04-29 13:27:30,132 INFO    MainThread:6389 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-04-29 13:29:27,459 WARNING MsgRouterThr:6389 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-04-29 13:29:27,461 INFO    MsgRouterThr:6389 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-04-29 13:29:28,297 INFO    MainThread:6389 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
